Resources:
  MyFunctionServiceRole3C357FF2:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: SampleStack/MyFunction/ServiceRole/Resource
  MyFunction3BAA72D1:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-ap-northeast-1
        S3Key: 2fc41b98bd3cb35bc4dc4cc8b4609fd38aca639e4e60bdb1812b3bb61e22a594.zip
      Handler: index.handler
      MemorySize: 512
      Role:
        Fn::GetAtt:
          - MyFunctionServiceRole3C357FF2
          - Arn
      Runtime: nodejs18.x
    DependsOn:
      - MyFunctionServiceRole3C357FF2
    Metadata:
      aws:cdk:path: SampleStack/MyFunction/Resource
      aws:asset:path: asset.2fc41b98bd3cb35bc4dc4cc8b4609fd38aca639e4e60bdb1812b3bb61e22a594
      aws:asset:is-bundled: true
      aws:asset:property: Code
  myApi10332170:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: myApi
    Metadata:
      aws:cdk:path: SampleStack/myApi/Resource
  myApiDeployment12138A1E22722400ea3a4d53f521371a1797f000:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Automatically created by the RestApi construct
      RestApiId:
        Ref: myApi10332170
    DependsOn:
      - myApiproxyANY5D46D965
      - myApiproxyB1F7DCCD
      - myApiANYF3D763C9
    Metadata:
      aws:cdk:path: SampleStack/myApi/Deployment/Resource
  myApiDeploymentStageprodBF46AA96:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId:
        Ref: myApiDeployment12138A1E22722400ea3a4d53f521371a1797f000
      RestApiId:
        Ref: myApi10332170
      StageName: prod
    Metadata:
      aws:cdk:path: SampleStack/myApi/DeploymentStage.prod/Resource
  myApiproxyB1F7DCCD:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - myApi10332170
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: myApi10332170
    Metadata:
      aws:cdk:path: SampleStack/myApi/Default/{proxy+}/Resource
  myApiproxyANYApiPermissionSampleStackmyApi99C27F24ANYproxyCE7FF87F:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - MyFunction3BAA72D1
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:ap-northeast-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: myApi10332170
            - /
            - Ref: myApiDeploymentStageprodBF46AA96
            - /*/*
    Metadata:
      aws:cdk:path: SampleStack/myApi/Default/{proxy+}/ANY/ApiPermission.SampleStackmyApi99C27F24.ANY..{proxy+}
  myApiproxyANYApiPermissionTestSampleStackmyApi99C27F24ANYproxyA8407EF4:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - MyFunction3BAA72D1
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:ap-northeast-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: myApi10332170
            - /test-invoke-stage/*/*
    Metadata:
      aws:cdk:path: SampleStack/myApi/Default/{proxy+}/ANY/ApiPermission.Test.SampleStackmyApi99C27F24.ANY..{proxy+}
  myApiproxyANY5D46D965:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - MyFunction3BAA72D1
                  - Arn
              - /invocations
      ResourceId:
        Ref: myApiproxyB1F7DCCD
      RestApiId:
        Ref: myApi10332170
    Metadata:
      aws:cdk:path: SampleStack/myApi/Default/{proxy+}/ANY/Resource
  myApiANYApiPermissionSampleStackmyApi99C27F24ANY245B2EA4:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - MyFunction3BAA72D1
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:ap-northeast-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: myApi10332170
            - /
            - Ref: myApiDeploymentStageprodBF46AA96
            - /*/
    Metadata:
      aws:cdk:path: SampleStack/myApi/Default/ANY/ApiPermission.SampleStackmyApi99C27F24.ANY..
  myApiANYApiPermissionTestSampleStackmyApi99C27F24ANYD86C28BF:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - MyFunction3BAA72D1
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:ap-northeast-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: myApi10332170
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: SampleStack/myApi/Default/ANY/ApiPermission.Test.SampleStackmyApi99C27F24.ANY..
  myApiANYF3D763C9:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - MyFunction3BAA72D1
                  - Arn
              - /invocations
      ResourceId:
        Fn::GetAtt:
          - myApi10332170
          - RootResourceId
      RestApiId:
        Ref: myApi10332170
    Metadata:
      aws:cdk:path: SampleStack/myApi/Default/ANY/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/01Qy26DQAz8ltwXt5BKPSdUPfURkQ9ADhiyPHYR9pYixL9Xu6RRTjMe2TO2E4hfXyDe4cRRUbZRpy+wnAWLVuHE+dJhfykxN7akhuErwLszhWhrlMYelsx2pNLKeFwV73NkJmE4eFC8h6MrWpIjMqnNDZa0MneTtDInGnvNrK1ZFQ66RqEJZ1g+QntGLIdBh4wbfaOhs3NPRrz6UJ0F67DNRjJi68aCQvhptL/zv3Jz2/gnydWWXtrYut4nVTjDu2lT+45vJ4OTx/FV+e9Aw08/SQJxAs+7hrWORmdE9wTZhn8DSrh3agEAAA==
    Metadata:
      aws:cdk:path: SampleStack/CDKMetadata/Default
Outputs:
  myApiEndpointF2DFDFB1:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: myApi10332170
          - .execute-api.ap-northeast-1.
          - Ref: AWS::URLSuffix
          - /
          - Ref: myApiDeploymentStageprodBF46AA96
          - /
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]

