Resources:
  ExampleTable114D508F:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TableName: ExampleTable
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: SampleStack/ExampleTable/Resource
  TestTable5769773A:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TableName: TestTable
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: SampleStack/TestTable/Resource
  TestTable2BDBB502F:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      TableName: TestTable2
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: SampleStack/TestTable2/Resource
  SqsMyQueueD0313F39:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 345600
      QueueName: SqsMyQueue
      VisibilityTimeout: 30
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Metadata:
      aws:cdk:path: SampleStack/SqsMyQueue/Resource
  ExecuteScriptServiceRole53BA6A10:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: SampleStack/ExecuteScript/ServiceRole/Resource
  ExecuteScriptServiceRoleDefaultPolicy63C5FAB6:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ConditionCheckItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
              - dynamodb:GetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:UpdateItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - ExampleTable114D508F
                  - Arn
              - Fn::GetAtt:
                  - TestTable2BDBB502F
                  - Arn
              - Fn::GetAtt:
                  - TestTable5769773A
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: ExecuteScriptServiceRoleDefaultPolicy63C5FAB6
      Roles:
        - Ref: ExecuteScriptServiceRole53BA6A10
    Metadata:
      aws:cdk:path: SampleStack/ExecuteScript/ServiceRole/DefaultPolicy/Resource
  ExecuteScriptB34670B8:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-ap-northeast-1
        S3Key: 4d92d52179a6d19e35cd6d6a98cdc2ca7558091708d3e9ec441c18491d0140b3.zip
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: http://host.docker.internal:4566
          SQS_ENDPOINT: http://localhost:4566
      Handler: index.handler
      MemorySize: 512
      Role:
        Fn::GetAtt:
          - ExecuteScriptServiceRole53BA6A10
          - Arn
      Runtime: nodejs18.x
      Timeout: 30
    DependsOn:
      - ExecuteScriptServiceRoleDefaultPolicy63C5FAB6
      - ExecuteScriptServiceRole53BA6A10
    Metadata:
      aws:cdk:path: SampleStack/ExecuteScript/Resource
      aws:asset:path: asset.4d92d52179a6d19e35cd6d6a98cdc2ca7558091708d3e9ec441c18491d0140b3
      aws:asset:is-bundled: true
      aws:asset:property: Code
  MyFunctionServiceRole3C357FF2:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: SampleStack/MyFunction/ServiceRole/Resource
  MyFunctionServiceRoleDefaultPolicyB705ABD4:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - dynamodb:BatchGetItem
              - dynamodb:BatchWriteItem
              - dynamodb:ConditionCheckItem
              - dynamodb:DeleteItem
              - dynamodb:DescribeTable
              - dynamodb:GetItem
              - dynamodb:GetRecords
              - dynamodb:GetShardIterator
              - dynamodb:PutItem
              - dynamodb:Query
              - dynamodb:Scan
              - dynamodb:UpdateItem
            Effect: Allow
            Resource:
              - Fn::GetAtt:
                  - ExampleTable114D508F
                  - Arn
              - Fn::GetAtt:
                  - TestTable2BDBB502F
                  - Arn
              - Fn::GetAtt:
                  - TestTable5769773A
                  - Arn
              - Ref: AWS::NoValue
        Version: "2012-10-17"
      PolicyName: MyFunctionServiceRoleDefaultPolicyB705ABD4
      Roles:
        - Ref: MyFunctionServiceRole3C357FF2
    Metadata:
      aws:cdk:path: SampleStack/MyFunction/ServiceRole/DefaultPolicy/Resource
  MyFunction3BAA72D1:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-ap-northeast-1
        S3Key: 67fc2bc8c84bb801fafd31306642269de2ad5ce07415a3c1fab3734074a21a9f.zip
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: http://host.docker.internal:4566
          SQS_ENDPOINT: http://localhost:4566
      Handler: index.handler
      MemorySize: 512
      Role:
        Fn::GetAtt:
          - MyFunctionServiceRole3C357FF2
          - Arn
      Runtime: nodejs18.x
      Timeout: 30
    DependsOn:
      - MyFunctionServiceRoleDefaultPolicyB705ABD4
      - MyFunctionServiceRole3C357FF2
    Metadata:
      aws:cdk:path: SampleStack/MyFunction/Resource
      aws:asset:path: asset.67fc2bc8c84bb801fafd31306642269de2ad5ce07415a3c1fab3734074a21a9f
      aws:asset:is-bundled: true
      aws:asset:property: Code
  SQSMyFunctionServiceRoleF1D5B74B:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
    Metadata:
      aws:cdk:path: SampleStack/SQSMyFunction/ServiceRole/Resource
  SQSMyFunctionServiceRoleDefaultPolicyFCEB1A0F:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - sqs:ChangeMessageVisibility
              - sqs:DeleteMessage
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
              - sqs:ReceiveMessage
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - SqsMyQueueD0313F39
                - Arn
        Version: "2012-10-17"
      PolicyName: SQSMyFunctionServiceRoleDefaultPolicyFCEB1A0F
      Roles:
        - Ref: SQSMyFunctionServiceRoleF1D5B74B
    Metadata:
      aws:cdk:path: SampleStack/SQSMyFunction/ServiceRole/DefaultPolicy/Resource
  SQSMyFunction9A6CA5A0:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Fn::Sub: cdk-hnb659fds-assets-${AWS::AccountId}-ap-northeast-1
        S3Key: eb623bca5af85acd11ff7576113f3ba7095adbdb0fdec8af7f56d3660890cbc7.zip
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: http://host.docker.internal:4566
          SQS_ENDPOINT: http://localhost:4566
      Handler: index.handler
      MemorySize: 512
      Role:
        Fn::GetAtt:
          - SQSMyFunctionServiceRoleF1D5B74B
          - Arn
      Runtime: nodejs20.x
      Timeout: 30
    DependsOn:
      - SQSMyFunctionServiceRoleDefaultPolicyFCEB1A0F
      - SQSMyFunctionServiceRoleF1D5B74B
    Metadata:
      aws:cdk:path: SampleStack/SQSMyFunction/Resource
      aws:asset:path: asset.eb623bca5af85acd11ff7576113f3ba7095adbdb0fdec8af7f56d3660890cbc7
      aws:asset:is-bundled: true
      aws:asset:property: Code
  SQSMyFunctionSqsEventSourceSampleStackSqsMyQueueA6964100F14ED9A2:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 5
      EventSourceArn:
        Fn::GetAtt:
          - SqsMyQueueD0313F39
          - Arn
      FunctionName:
        Ref: SQSMyFunction9A6CA5A0
    Metadata:
      aws:cdk:path: SampleStack/SQSMyFunction/SqsEventSource:SampleStackSqsMyQueueA6964100/Resource
  myApi10332170:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: myApi
    Metadata:
      aws:cdk:path: SampleStack/myApi/Resource
  myApiDeployment12138A1E22722400ea3a4d53f521371a1797f000:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description: Automatically created by the RestApi construct
      RestApiId:
        Ref: myApi10332170
    DependsOn:
      - myApiproxyANY5D46D965
      - myApiproxyB1F7DCCD
      - myApiANYF3D763C9
    Metadata:
      aws:cdk:path: SampleStack/myApi/Deployment/Resource
  myApiDeploymentStageprodBF46AA96:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId:
        Ref: myApiDeployment12138A1E22722400ea3a4d53f521371a1797f000
      RestApiId:
        Ref: myApi10332170
      StageName: prod
    Metadata:
      aws:cdk:path: SampleStack/myApi/DeploymentStage.prod/Resource
  myApiproxyB1F7DCCD:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt:
          - myApi10332170
          - RootResourceId
      PathPart: "{proxy+}"
      RestApiId:
        Ref: myApi10332170
    Metadata:
      aws:cdk:path: SampleStack/myApi/Default/{proxy+}/Resource
  myApiproxyANYApiPermissionSampleStackmyApi99C27F24ANYproxyCE7FF87F:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - MyFunction3BAA72D1
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:ap-northeast-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: myApi10332170
            - /
            - Ref: myApiDeploymentStageprodBF46AA96
            - /*/*
    Metadata:
      aws:cdk:path: SampleStack/myApi/Default/{proxy+}/ANY/ApiPermission.SampleStackmyApi99C27F24.ANY..{proxy+}
  myApiproxyANYApiPermissionTestSampleStackmyApi99C27F24ANYproxyA8407EF4:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - MyFunction3BAA72D1
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:ap-northeast-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: myApi10332170
            - /test-invoke-stage/*/*
    Metadata:
      aws:cdk:path: SampleStack/myApi/Default/{proxy+}/ANY/ApiPermission.Test.SampleStackmyApi99C27F24.ANY..{proxy+}
  myApiproxyANY5D46D965:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - MyFunction3BAA72D1
                  - Arn
              - /invocations
      ResourceId:
        Ref: myApiproxyB1F7DCCD
      RestApiId:
        Ref: myApi10332170
    Metadata:
      aws:cdk:path: SampleStack/myApi/Default/{proxy+}/ANY/Resource
  myApiANYApiPermissionSampleStackmyApi99C27F24ANY245B2EA4:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - MyFunction3BAA72D1
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:ap-northeast-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: myApi10332170
            - /
            - Ref: myApiDeploymentStageprodBF46AA96
            - /*/
    Metadata:
      aws:cdk:path: SampleStack/myApi/Default/ANY/ApiPermission.SampleStackmyApi99C27F24.ANY..
  myApiANYApiPermissionTestSampleStackmyApi99C27F24ANYD86C28BF:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - MyFunction3BAA72D1
          - Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
          - ""
          - - "arn:aws:execute-api:ap-northeast-1:"
            - Ref: AWS::AccountId
            - ":"
            - Ref: myApi10332170
            - /test-invoke-stage/*/
    Metadata:
      aws:cdk:path: SampleStack/myApi/Default/ANY/ApiPermission.Test.SampleStackmyApi99C27F24.ANY..
  myApiANYF3D763C9:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: ANY
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri:
          Fn::Join:
            - ""
            - - arn:aws:apigateway:ap-northeast-1:lambda:path/2015-03-31/functions/
              - Fn::GetAtt:
                  - MyFunction3BAA72D1
                  - Arn
              - /invocations
      ResourceId:
        Fn::GetAtt:
          - myApi10332170
          - RootResourceId
      RestApiId:
        Ref: myApi10332170
    Metadata:
      aws:cdk:path: SampleStack/myApi/Default/ANY/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/22QQVPCMBCFfwv3sEpxxjOgnkSxeGe27YKBNqndDdjJ5L87SSvDwdN7+2b2y9tkMHt8gNkELzwtq9O01gX4rWB5Unjhna96g42tCvCfWNSkVnuTTFD8zeA/HLkUJhNUjU1R4c7Yio4Mb0lenClFW6M0NuBzO1CSbmytyz6OgwuK5ztkJmFYRFE8h6UrTyRLZBrx4Fd7c6U+n8nI1rqupDW2rTaHyPs/3VDXaGZtTVDY6gMKXbAH/5q4ObEsWp3ajfaJ2tr2DRmJ6c20FTykOwaTE6e3UstNZ3/6v2SkDX5N8mWrGA0uhOumSvdG2tj13Unr5HY9qPivcOS7c5bBLIP7yZG1nnbOiG4I8kF/AVKjWT7TAQAA
    Metadata:
      aws:cdk:path: SampleStack/CDKMetadata/Default
Outputs:
  myApiEndpointF2DFDFB1:
    Value:
      Fn::Join:
        - ""
        - - https://
          - Ref: myApi10332170
          - .execute-api.ap-northeast-1.
          - Ref: AWS::URLSuffix
          - /
          - Ref: myApiDeploymentStageprodBF46AA96
          - /
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]

